stages:
  - test
jobs:
  include:
    - stage: test
      dist: trusty
      language: node_js
      node_js: "10"
      cache:
        timeout: 1000
        yarn: true
        directories:
          - node_modules
      before_install:
        - nvm install
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
      before_script:
        - source .dev-env.sh
        - yarn audit
        - yarn audit --cwd src/www
      script:
        - yarn lint
        - yarn test
